modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://www.github.com/xfacthd/advancedtechnology"
license="LGPL v3"

[[mods]]
modId="advtech"
version="${file.jarVersion}"
displayName="AdvancedTechnology"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="XFactHD"
description='''
'''
[[dependencies.advtech]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.advtech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.advtech]]
    modId="jei"
    mandatory=false
    versionRange="[9.2.1.69,)"
    ordering="NONE"
    side="BOTH"
